### ISSUE TITLE
Issue discovered on `cascading-hadoop2-common/src/test/java/cascading/tap/hadoop/DistCacheTapPlatformTest.java` with `Use `Files#createTempDirectory``

### ISSUE THREAD

**Issue by JLLeitschuh** [moderneinc/support-public#18] opened 2023-01-12 15:15 UTC
### Problem
> Describe the issue you are experiencing.

### Expected behavior
> Describe what you expected to see.

### Example diff

**From:** `cascading-hadoop2-common/src/test/java/cascading/tap/hadoop/DistCacheTapPlatformTest.java`

```diff
    File dir = File.createTempFile( "distcachetap", Long.toString( System.nanoTime() ) );
if( dir.exists() )
{
-      if( dir.isDirectory() )
+      {{93003c08-bb92-4e3c-9f29-2ae108bf6896}}if( dir.isDirectory() )
  FileUtils.deleteDirectory( dir );
else
-        dir.delete();
+        dir.delete();{{93003c08-bb92-4e3c-9f29-2ae108bf6896}}
}
dir.mkdirs();
String[] data = new String[]{"1 A", "2 B", "3 C", "4 D", "5 E"};
```

#### Recipes in example diff:
- `org.openrewrite.java.security.UseFilesCreateTempDirectory`

### References:
- [View original result](https://public.moderne.io/results/E8Mj9/details/eyJfX3R5cGVuYW1lIjoiR2l0SHViUmVwb3NpdG9yeSIsImlkIjoiR2l0SHViUmVwb3NpdG9yeX5+Z2l0aHViLmNvbX5+Y3dlbnNlbC9jYXNjYWRpbmd+fjQuMCIsIm9yaWdpbiI6ImdpdGh1Yi5jb20iLCJwYXRoIjoiY3dlbnNlbC9jYXNjYWRpbmciLCJicmFuY2giOiI0LjAiLCJvcmdhbml6YXRpb24iOiJjd2Vuc2VsIiwibmFtZSI6ImNhc2NhZGluZyIsImluZ2VzdGVkIjpudWxsfQ==?onlyShowErrors=true&referrer=%2Fresults%2FE8Mj9)
- Recipe ID: `org.openrewrite.java.security.UseFilesCreateTempDirectory`
- Recipe Name: `Use `Files#createTempDirectory``
- Repository: `cwensel/cascading/4.0`
- Created at Thu Jan 12 2023 10:14:52 GMT-0500 (Eastern Standard Time)

### Exception

```
java.lang.NullPointerException: Cannot invoke "org.openrewrite.java.tree.JRightPadded.getElement()" because "this.body" is null
  org.openrewrite.java.tree.J$If$Else.getBody(J.java:2445)
  org.openrewrite.java.DeleteStatement.visitIf(DeleteStatement.java:54)
  org.openrewrite.java.DeleteStatement.visitIf(DeleteStatement.java:30)
  org.openrewrite.java.tree.J$If.acceptJava(J.java:2410)
  org.openrewrite.java.tree.J.accept(J.java:64)
  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:276)
  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:356)
  org.openrewrite.java.JavaVisitor.visitRightPadded(JavaVisitor.java:1261)
  ...
```

**Comment by sjungling** [comment] 2023-01-12 18:47
duplicate of #19

**Comment by JLLeitschuh** [comment] 2023-01-12 19:47
I think they both have the same root cause

**Closed** 2023-01-13 17:34 UTC
Labels: enhancement
